--------------------------------------------------------
--  文件已创建 - 星期二-四月-01-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ANALYSISSETTING_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "EMI"."ANALYSISSETTING_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ANALYSISTYPE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "EMI"."ANALYSISTYPE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ANALYSIS_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "EMI"."ANALYSIS_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CHANNELSETTING_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "EMI"."CHANNELSETTING_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COLORSETTING_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "EMI"."COLORSETTING_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMI_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "EMI"."EMI_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EQUIPMENTPARAMETER_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "EMI"."EQUIPMENTPARAMETER_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LINKCONFIGURATION_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "EMI"."LINKCONFIGURATION_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REGION_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "EMI"."REGION_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SITE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "EMI"."SITE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TASK_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "EMI"."TASK_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USERS_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "EMI"."USERS_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ANALYSIS
--------------------------------------------------------

  CREATE TABLE "EMI"."ANALYSIS" 
   (	"ID" NUMBER, 
	"ANALYZER" NUMBER, 
	"TYPE" NUMBER, 
	"SETTING" NUMBER, 
	"ANALYZETIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ANALYSISSETTING
--------------------------------------------------------

  CREATE TABLE "EMI"."ANALYSISSETTING" 
   (	"PRIMARYEMIFILE" NUMBER, 
	"SECONDARYEMIFILE" NUMBER, 
	"CHANNELSETTINGFILE" NUMBER, 
	"LINKCONFIGURATIONFILE" NUMBER, 
	"USEMANUALLINKCONFIGURATION" NUMBER(1,0) DEFAULT 0, 
	"MANUALLINKCONFIGURATION" NUMBER DEFAULT 0, 
	"EQUIPMENTPARAMETERFILE" NUMBER, 
	"STARTFEQ" NUMBER(*,3), 
	"ENDFREQ" NUMBER(*,3), 
	"DELTAPOWERLIMIT" NUMBER(*,3), 
	"CHANNELPOWERLIMIT" NUMBER(*,3), 
	"USEDELTAPOWERLIMIT" VARCHAR2(20 BYTE), 
	"USECHANNELPOWERLIMIT" VARCHAR2(20 BYTE), 
	"CHANNELPREFERRED" NUMBER(1,0) DEFAULT 0, 
	"DISPLAYCHANNEL" NUMBER(1,0) DEFAULT 0, 
	"ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ANALYSISTYPE
--------------------------------------------------------

  CREATE TABLE "EMI"."ANALYSISTYPE" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CHANNELSETTINGFILE
--------------------------------------------------------

  CREATE TABLE "EMI"."CHANNELSETTINGFILE" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(128 BYTE), 
	"FILENAME" VARCHAR2(64 BYTE), 
	"FILECONTENT" BLOB, 
	"MD5" VARCHAR2(128 BYTE), 
	"PARSEDATA" BLOB, 
	"UPLOADER" VARCHAR2(32 BYTE), 
	"CREATETIME" VARCHAR2(32 BYTE), 
	"DELETED" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("FILECONTENT") STORE AS BASICFILE "SYS_LOB0000073761C00004$$"(
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PARSEDATA") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table COLORSETTINGFILE
--------------------------------------------------------

  CREATE TABLE "EMI"."COLORSETTINGFILE" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(128 BYTE), 
	"FILENAME" VARCHAR2(64 BYTE), 
	"FILECONTENT" BLOB, 
	"MD5" VARCHAR2(128 BYTE), 
	"PARSEDATA" BLOB, 
	"UPLOADER" VARCHAR2(32 BYTE), 
	"CREATETIME" DATE, 
	"DELETED" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("FILECONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("PARSEDATA") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table EMIFILE
--------------------------------------------------------

  CREATE TABLE "EMI"."EMIFILE" 
   (	"ID" NUMBER(*,0), 
	"TITLE" VARCHAR2(128 BYTE), 
	"FILENAME" VARCHAR2(64 BYTE), 
	"FILECONTENT" BLOB, 
	"MD5" VARCHAR2(128 BYTE), 
	"PARSEDATA" BLOB, 
	"UPLOADER" VARCHAR2(32 BYTE), 
	"CREATETIME" VARCHAR2(32 BYTE), 
	"SITEID" VARCHAR2(32 BYTE), 
	"TESTER" VARCHAR2(32 BYTE), 
	"TESTTIME" VARCHAR2(32 BYTE), 
	"DELETED" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("FILECONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PARSEDATA") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table EQUIPMENTPARAMETERFILE
--------------------------------------------------------

  CREATE TABLE "EMI"."EQUIPMENTPARAMETERFILE" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(128 BYTE), 
	"FILENAME" VARCHAR2(64 BYTE), 
	"FILECONTENT" BLOB, 
	"MD5" VARCHAR2(128 BYTE), 
	"PARSEDATA" BLOB, 
	"UPLOADER" VARCHAR2(32 BYTE), 
	"CREATETIME" VARCHAR2(32 BYTE), 
	"DELETED" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("FILECONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PARSEDATA") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table LINKCONFIGURATIONFILE
--------------------------------------------------------

  CREATE TABLE "EMI"."LINKCONFIGURATIONFILE" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(128 BYTE), 
	"FILENAME" VARCHAR2(64 BYTE), 
	"FILECONTENT" BLOB, 
	"MD5" VARCHAR2(128 BYTE), 
	"PARSEDATA" BLOB, 
	"UPLOADER" VARCHAR2(32 BYTE), 
	"CREATETIME" VARCHAR2(32 BYTE), 
	"DELETED" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("FILECONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PARSEDATA") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table REGION
--------------------------------------------------------

  CREATE TABLE "EMI"."REGION" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(64 BYTE), 
	"CREATOR" NUMBER, 
	"CREATETIME" DATE, 
	"DELETED" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGION_CHANNELSETTINGFILE
--------------------------------------------------------

  CREATE TABLE "EMI"."REGION_CHANNELSETTINGFILE" 
   (	"REGION_ID" NUMBER, 
	"CHANNELSETTINGFILE_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGION_EQUIPMENTPARAMETERFILE
--------------------------------------------------------

  CREATE TABLE "EMI"."REGION_EQUIPMENTPARAMETERFILE" 
   (	"REGION_ID" NUMBER, 
	"EQUIPMENTPARAMETERFILE_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGION_LINKCONFIGURATIONFILE
--------------------------------------------------------

  CREATE TABLE "EMI"."REGION_LINKCONFIGURATIONFILE" 
   (	"REION_ID" NUMBER, 
	"LINKCONFIGURATIONFILE_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGION_MANAGER
--------------------------------------------------------

  CREATE TABLE "EMI"."REGION_MANAGER" 
   (	"REGION_ID" NUMBER, 
	"MANAGER_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGION_SITE
--------------------------------------------------------

  CREATE TABLE "EMI"."REGION_SITE" 
   (	"REGION_ID" NUMBER, 
	"SITE_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGION_STRUCTURE
--------------------------------------------------------

  CREATE TABLE "EMI"."REGION_STRUCTURE" 
   (	"REGION_ID" NUMBER, 
	"SUB_REGION_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SITE
--------------------------------------------------------

  CREATE TABLE "EMI"."SITE" 
   (	"ID" NUMBER, 
	"SITEID" VARCHAR2(64 BYTE), 
	"SAMID" VARCHAR2(64 BYTE), 
	"SITENAME" VARCHAR2(64 BYTE), 
	"SITETYPE" VARCHAR2(64 BYTE), 
	"LONGITUDE" NUMBER(*,3) DEFAULT 0, 
	"LATITUDE" NUMBER(*,3) DEFAULT 0, 
	"BSC" VARCHAR2(64 BYTE), 
	"RNC" VARCHAR2(64 BYTE), 
	"DELETED" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TASK
--------------------------------------------------------

  CREATE TABLE "EMI"."TASK" 
   (	"ID" NUMBER, 
	"REGIONID" NUMBER, 
	"NAME" VARCHAR2(64 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"CREATOR" NUMBER, 
	"CREATETIME" DATE, 
	"DELETED" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TASK_ANALYSIS
--------------------------------------------------------

  CREATE TABLE "EMI"."TASK_ANALYSIS" 
   (	"TASK_ID" NUMBER, 
	"ANALYSIS_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "EMI"."USERS" 
   (	"ID" NUMBER, 
	"USERID" VARCHAR2(32 BYTE), 
	"PASSWORD" VARCHAR2(128 BYTE), 
	"ROLE" VARCHAR2(16 BYTE) DEFAULT 'normal', 
	"LOCKED" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_TASK
--------------------------------------------------------

  CREATE TABLE "EMI"."USER_TASK" 
   (	"USER_ID" NUMBER, 
	"TASK_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into EMI.ANALYSIS
SET DEFINE OFF;
REM INSERTING into EMI.ANALYSISSETTING
SET DEFINE OFF;
REM INSERTING into EMI.ANALYSISTYPE
SET DEFINE OFF;
REM INSERTING into EMI.CHANNELSETTINGFILE
SET DEFINE OFF;
Insert into EMI.CHANNELSETTINGFILE (ID,TITLE,FILENAME,MD5,UPLOADER,CREATETIME,DELETED) values (2014013023590876500,'01-channel setting template.xlsx (abc, 2014/01/30 23:59:08)','01-channel setting template.xlsx','532C87DF2467ACD7303C2D78A4C6346B','abc','2014/01/30 23:59:08',0);
REM INSERTING into EMI.COLORSETTINGFILE
SET DEFINE OFF;
REM INSERTING into EMI.EMIFILE
SET DEFINE OFF;
Insert into EMI.EMIFILE (ID,TITLE,FILENAME,MD5,UPLOADER,CREATETIME,SITEID,TESTER,TESTTIME,DELETED) values (2014021623170209000,'ANTONIONE.emi (test, 2014/02/16 23:17:02)','ANTONIONE.emi','F0B53FAC984A20D4CE67FC177C1B0EE6','test','2014/02/16 23:17:02','ANTONIONE','1','20120915082138',0);
Insert into EMI.EMIFILE (ID,TITLE,FILENAME,MD5,UPLOADER,CREATETIME,SITEID,TESTER,TESTTIME,DELETED) values (2014021623170700600,'DINGALAN_20120918102225.emi (test, 2014/02/16 23:17:07)','DINGALAN_20120918102225.emi','D1B17772A6E372BD97EC6D16571A3CE0','test','2014/02/16 23:17:07','DINGALAN','1','20120918102225',0);
Insert into EMI.EMIFILE (ID,TITLE,FILENAME,MD5,UPLOADER,CREATETIME,SITEID,TESTER,TESTTIME,DELETED) values (2014021623170764000,'020188-2d_020188_20120518175909.emi (test, 2014/02/16 23:17:07)','020188-2d_020188_20120518175909.emi','FC632A5892425057FA62B71FFADAE47D','test','2014/02/16 23:17:07','020188','1','20120518175909',0);
Insert into EMI.EMIFILE (ID,TITLE,FILENAME,MD5,UPLOADER,CREATETIME,SITEID,TESTER,TESTTIME,DELETED) values (2014021623170903600,'027002-2d_027002_20120518090125.emi (test, 2014/02/16 23:17:09)','027002-2d_027002_20120518090125.emi','D476D3C44AE180746B0B613E35F436F8','test','2014/02/16 23:17:09','027002','1','20120518090125',0);
Insert into EMI.EMIFILE (ID,TITLE,FILENAME,MD5,UPLOADER,CREATETIME,SITEID,TESTER,TESTTIME,DELETED) values (2014021623171057700,'BONGABON_TEMPLETE_20120917164414.emi (test, 2014/02/16 23:17:10)','BONGABON_TEMPLETE_20120917164414.emi','B488F7806CD6993167287F3099AA6794','test','2014/02/16 23:17:10','TEMPLETE','1','20120917164414',0);
Insert into EMI.EMIFILE (ID,TITLE,FILENAME,MD5,UPLOADER,CREATETIME,SITEID,TESTER,TESTTIME,DELETED) values (2014021623171106500,'FTIMAPANT20120917135523.emi (test, 2014/02/16 23:17:11)','FTIMAPANT20120917135523.emi','AA1980D2386EFB428F8ED73829045227','test','2014/02/16 23:17:11','TEMPLETE','1','20120917135523',0);
Insert into EMI.EMIFILE (ID,TITLE,FILENAME,MD5,UPLOADER,CREATETIME,SITEID,TESTER,TESTTIME,DELETED) values (2014021623171172200,'PNTBNGNTEMPLETE_20120917120648.emi (test, 2014/02/16 23:17:11)','PNTBNGNTEMPLETE_20120917120648.emi','37A641725B4B7172394E4B072FF38977','test','2014/02/16 23:17:11','TEMPLETE','1','20120917120648',0);
Insert into EMI.EMIFILE (ID,TITLE,FILENAME,MD5,UPLOADER,CREATETIME,SITEID,TESTER,TESTTIME,DELETED) values (2014021623171214400,'TALAVERASE_TEMPLETE_20120917092956.emi (test, 2014/02/16 23:17:12)','TALAVERASE_TEMPLETE_20120917092956.emi','92D3D6F398E19A64C135E18BB57C1EF1','test','2014/02/16 23:17:12','TEMPLETE','1','20120917092956',0);
Insert into EMI.EMIFILE (ID,TITLE,FILENAME,MD5,UPLOADER,CREATETIME,SITEID,TESTER,TESTTIME,DELETED) values (2014021623171326400,'TALAVERA_TEMPLETE_20120916152528.emi (test, 2014/02/16 23:17:13)','TALAVERA_TEMPLETE_20120916152528.emi','1283E5B71C2D03F7ECE8BAA118342121','test','2014/02/16 23:17:13','TEMPLETE','1','20120916152528',0);
REM INSERTING into EMI.EQUIPMENTPARAMETERFILE
SET DEFINE OFF;
Insert into EMI.EQUIPMENTPARAMETERFILE (ID,TITLE,FILENAME,MD5,UPLOADER,CREATETIME,DELETED) values (2014021222123191200,'03-Equipment parameter template.xlsx (abc, 2014/02/12 22:12:31)','03-Equipment parameter template.xlsx','6A666BBB019F56BB7764055D67F6172B','abc','2014/02/12 22:12:31',0);
REM INSERTING into EMI.LINKCONFIGURATIONFILE
SET DEFINE OFF;
Insert into EMI.LINKCONFIGURATIONFILE (ID,TITLE,FILENAME,MD5,UPLOADER,CREATETIME,DELETED) values (2014021222122001400,'02-Link configuration import template.xlsx (abc, 2014/02/12 22:12:20)','02-Link configuration import template.xlsx','5E8D31E618DB607D580248C513AB4B63','abc','2014/02/12 22:12:20',0);
REM INSERTING into EMI.REGION
SET DEFINE OFF;
REM INSERTING into EMI.REGION_CHANNELSETTINGFILE
SET DEFINE OFF;
REM INSERTING into EMI.REGION_EQUIPMENTPARAMETERFILE
SET DEFINE OFF;
REM INSERTING into EMI.REGION_LINKCONFIGURATIONFILE
SET DEFINE OFF;
REM INSERTING into EMI.REGION_MANAGER
SET DEFINE OFF;
REM INSERTING into EMI.REGION_SITE
SET DEFINE OFF;
REM INSERTING into EMI.REGION_STRUCTURE
SET DEFINE OFF;
REM INSERTING into EMI.SITE
SET DEFINE OFF;
REM INSERTING into EMI.TASK
SET DEFINE OFF;
REM INSERTING into EMI.TASK_ANALYSIS
SET DEFINE OFF;
REM INSERTING into EMI.USERS
SET DEFINE OFF;
Insert into EMI.USERS (ID,USERID,PASSWORD,ROLE,LOCKED) values (50,'admin','12017f92d4f5ee2d497cb189331592f0','admin',0);
Insert into EMI.USERS (ID,USERID,PASSWORD,ROLE,LOCKED) values (51,'test1','15be76c3d3a0cb61ebb10aec957f75ac','normal',0);
Insert into EMI.USERS (ID,USERID,PASSWORD,ROLE,LOCKED) values (52,'test2','0a23faf342db5a6b3babf122897493e3','normal',0);
Insert into EMI.USERS (ID,USERID,PASSWORD,ROLE,LOCKED) values (53,'test3','5bfc244f805500c62781bdfcc6cd9b55','normal',0);
Insert into EMI.USERS (ID,USERID,PASSWORD,ROLE,LOCKED) values (54,'test4','51c7e434b0e07b70f2a1a4894fb18541','normal',0);
Insert into EMI.USERS (ID,USERID,PASSWORD,ROLE,LOCKED) values (55,'test5','d01604995fe3643604f74958ed037d2f','normal',0);
REM INSERTING into EMI.USER_TASK
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ANALYSISSETTING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."ANALYSISSETTING_PK" ON "EMI"."ANALYSISSETTING" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ANALYSISTYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."ANALYSISTYPE_PK" ON "EMI"."ANALYSISTYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ANALYSIS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."ANALYSIS_PK" ON "EMI"."ANALYSIS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CHANNELSETTINGFILE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."CHANNELSETTINGFILE_UK1" ON "EMI"."CHANNELSETTINGFILE" ("MD5") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  ALTER INDEX "EMI"."CHANNELSETTINGFILE_UK1"  UNUSABLE;
--------------------------------------------------------
--  DDL for Index CHANNEL_SETTING_FILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."CHANNEL_SETTING_FILE_PK" ON "EMI"."CHANNELSETTINGFILE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COLORSETTINGFILE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."COLORSETTINGFILE_UK1" ON "EMI"."COLORSETTINGFILE" ("MD5") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COLOR_SETTING_FILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."COLOR_SETTING_FILE_PK" ON "EMI"."COLORSETTINGFILE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMIFILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."EMIFILE_PK" ON "EMI"."EMIFILE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMIFILE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."EMIFILE_UK1" ON "EMI"."EMIFILE" ("MD5") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EQUIPMENTPARAMETERFILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."EQUIPMENTPARAMETERFILE_PK" ON "EMI"."EQUIPMENTPARAMETERFILE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EQUIPMENTPARAMETERFILE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."EQUIPMENTPARAMETERFILE_UK1" ON "EMI"."EQUIPMENTPARAMETERFILE" ("MD5") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LINKCONFIGURATIONFILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."LINKCONFIGURATIONFILE_PK" ON "EMI"."LINKCONFIGURATIONFILE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LINKCONFIGURATIONFILE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."LINKCONFIGURATIONFILE_UK1" ON "EMI"."LINKCONFIGURATIONFILE" ("MD5") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REGION_CHANNELSETTINGFILE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."REGION_CHANNELSETTINGFILE_UK1" ON "EMI"."REGION_CHANNELSETTINGFILE" ("REGION_ID", "CHANNELSETTINGFILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REGION_EQUIPMENTPARAMETER_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."REGION_EQUIPMENTPARAMETER_UK1" ON "EMI"."REGION_EQUIPMENTPARAMETERFILE" ("REGION_ID", "EQUIPMENTPARAMETERFILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REGION_LINKCONFIGURATIONF_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."REGION_LINKCONFIGURATIONF_UK1" ON "EMI"."REGION_LINKCONFIGURATIONFILE" ("REION_ID", "LINKCONFIGURATIONFILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REGION_MANAGER_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."REGION_MANAGER_UK1" ON "EMI"."REGION_MANAGER" ("REGION_ID", "MANAGER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REGION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."REGION_PK" ON "EMI"."REGION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REGION_SITE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."REGION_SITE_UK1" ON "EMI"."REGION_SITE" ("REGION_ID", "SITE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REGION_STRUCTURE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."REGION_STRUCTURE_PK" ON "EMI"."REGION_STRUCTURE" ("REGION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SITE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."SITE_PK" ON "EMI"."SITE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SITE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."SITE_UK1" ON "EMI"."SITE" ("SITEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TASK_ANALYSIS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."TASK_ANALYSIS_UK1" ON "EMI"."TASK_ANALYSIS" ("TASK_ID", "ANALYSIS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TASK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."TASK_PK" ON "EMI"."TASK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."USERS_PK" ON "EMI"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."USERS_UK1" ON "EMI"."USERS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USER_TASK_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMI"."USER_TASK_UK1" ON "EMI"."USER_TASK" ("USER_ID", "TASK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ANALYSIS
--------------------------------------------------------

  ALTER TABLE "EMI"."ANALYSIS" ADD CONSTRAINT "ANALYSIS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EMI"."ANALYSIS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ANALYSISSETTING
--------------------------------------------------------

  ALTER TABLE "EMI"."ANALYSISSETTING" ADD CONSTRAINT "ANALYSISSETTING_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EMI"."ANALYSISSETTING" MODIFY ("PRIMARYEMIFILE" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."ANALYSISSETTING" MODIFY ("CHANNELSETTINGFILE" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."ANALYSISSETTING" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ANALYSISTYPE
--------------------------------------------------------

  ALTER TABLE "EMI"."ANALYSISTYPE" ADD CONSTRAINT "ANALYSISTYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EMI"."ANALYSISTYPE" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."ANALYSISTYPE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHANNELSETTINGFILE
--------------------------------------------------------

  ALTER TABLE "EMI"."CHANNELSETTINGFILE" ADD CONSTRAINT "CHANNEL_SETTING_FILE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EMI"."CHANNELSETTINGFILE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."CHANNELSETTINGFILE" MODIFY ("TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."CHANNELSETTINGFILE" MODIFY ("FILENAME" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."CHANNELSETTINGFILE" MODIFY ("FILECONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."CHANNELSETTINGFILE" MODIFY ("MD5" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."CHANNELSETTINGFILE" MODIFY ("PARSEDATA" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."CHANNELSETTINGFILE" MODIFY ("UPLOADER" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."CHANNELSETTINGFILE" MODIFY ("CREATETIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COLORSETTINGFILE
--------------------------------------------------------

  ALTER TABLE "EMI"."COLORSETTINGFILE" ADD CONSTRAINT "COLOR_SETTING_FILE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EMI"."COLORSETTINGFILE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."COLORSETTINGFILE" MODIFY ("TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."COLORSETTINGFILE" MODIFY ("FILENAME" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."COLORSETTINGFILE" MODIFY ("FILECONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."COLORSETTINGFILE" MODIFY ("MD5" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."COLORSETTINGFILE" MODIFY ("PARSEDATA" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."COLORSETTINGFILE" MODIFY ("UPLOADER" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."COLORSETTINGFILE" MODIFY ("CREATETIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMIFILE
--------------------------------------------------------

  ALTER TABLE "EMI"."EMIFILE" ADD CONSTRAINT "EMIFILE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EMI"."EMIFILE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."EMIFILE" MODIFY ("TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."EMIFILE" MODIFY ("FILENAME" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."EMIFILE" MODIFY ("FILECONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."EMIFILE" MODIFY ("MD5" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."EMIFILE" MODIFY ("PARSEDATA" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."EMIFILE" MODIFY ("UPLOADER" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."EMIFILE" MODIFY ("CREATETIME" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."EMIFILE" MODIFY ("SITEID" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."EMIFILE" MODIFY ("TESTER" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."EMIFILE" MODIFY ("TESTTIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPMENTPARAMETERFILE
--------------------------------------------------------

  ALTER TABLE "EMI"."EQUIPMENTPARAMETERFILE" ADD CONSTRAINT "EQUIPMENTPARAMETERFILE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EMI"."EQUIPMENTPARAMETERFILE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."EQUIPMENTPARAMETERFILE" MODIFY ("TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."EQUIPMENTPARAMETERFILE" MODIFY ("FILENAME" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."EQUIPMENTPARAMETERFILE" MODIFY ("FILECONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."EQUIPMENTPARAMETERFILE" MODIFY ("MD5" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."EQUIPMENTPARAMETERFILE" MODIFY ("PARSEDATA" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."EQUIPMENTPARAMETERFILE" MODIFY ("UPLOADER" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."EQUIPMENTPARAMETERFILE" MODIFY ("CREATETIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LINKCONFIGURATIONFILE
--------------------------------------------------------

  ALTER TABLE "EMI"."LINKCONFIGURATIONFILE" ADD CONSTRAINT "LINKCONFIGURATIONFILE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EMI"."LINKCONFIGURATIONFILE" ADD CONSTRAINT "LINKCONFIGURATIONFILE_UK1" UNIQUE ("MD5")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EMI"."LINKCONFIGURATIONFILE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."LINKCONFIGURATIONFILE" MODIFY ("TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."LINKCONFIGURATIONFILE" MODIFY ("FILENAME" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."LINKCONFIGURATIONFILE" MODIFY ("FILECONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."LINKCONFIGURATIONFILE" MODIFY ("MD5" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."LINKCONFIGURATIONFILE" MODIFY ("PARSEDATA" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."LINKCONFIGURATIONFILE" MODIFY ("UPLOADER" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."LINKCONFIGURATIONFILE" MODIFY ("CREATETIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REGION
--------------------------------------------------------

  ALTER TABLE "EMI"."REGION" ADD CONSTRAINT "REGION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EMI"."REGION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."REGION" MODIFY ("CREATOR" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."REGION" MODIFY ("CREATETIME" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."REGION" MODIFY ("DELETED" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REGION_CHANNELSETTINGFILE
--------------------------------------------------------

  ALTER TABLE "EMI"."REGION_CHANNELSETTINGFILE" ADD CONSTRAINT "REGION_CHANNELSETTINGFILE_UK1" UNIQUE ("REGION_ID", "CHANNELSETTINGFILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REGION_EQUIPMENTPARAMETERFILE
--------------------------------------------------------

  ALTER TABLE "EMI"."REGION_EQUIPMENTPARAMETERFILE" ADD CONSTRAINT "REGION_EQUIPMENTPARAMETER_UK1" UNIQUE ("REGION_ID", "EQUIPMENTPARAMETERFILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REGION_LINKCONFIGURATIONFILE
--------------------------------------------------------

  ALTER TABLE "EMI"."REGION_LINKCONFIGURATIONFILE" ADD CONSTRAINT "REGION_LINKCONFIGURATIONF_UK1" UNIQUE ("REION_ID", "LINKCONFIGURATIONFILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REGION_MANAGER
--------------------------------------------------------

  ALTER TABLE "EMI"."REGION_MANAGER" ADD CONSTRAINT "REGION_MANAGER_UK1" UNIQUE ("REGION_ID", "MANAGER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REGION_SITE
--------------------------------------------------------

  ALTER TABLE "EMI"."REGION_SITE" ADD CONSTRAINT "REGION_SITE_UK1" UNIQUE ("REGION_ID", "SITE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REGION_STRUCTURE
--------------------------------------------------------

  ALTER TABLE "EMI"."REGION_STRUCTURE" ADD CONSTRAINT "REGION_STRUCTURE_PK" PRIMARY KEY ("REGION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EMI"."REGION_STRUCTURE" MODIFY ("REGION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."REGION_STRUCTURE" MODIFY ("SUB_REGION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SITE
--------------------------------------------------------

  ALTER TABLE "EMI"."SITE" ADD CONSTRAINT "SITE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EMI"."SITE" ADD CONSTRAINT "SITE_UK1" UNIQUE ("SITEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EMI"."SITE" MODIFY ("SITEID" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."SITE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TASK
--------------------------------------------------------

  ALTER TABLE "EMI"."TASK" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."TASK" MODIFY ("CREATETIME" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."TASK" MODIFY ("REGIONID" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."TASK" ADD CONSTRAINT "TASK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TASK_ANALYSIS
--------------------------------------------------------

  ALTER TABLE "EMI"."TASK_ANALYSIS" ADD CONSTRAINT "TASK_ANALYSIS_UK1" UNIQUE ("TASK_ID", "ANALYSIS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "EMI"."USERS" MODIFY ("USERID" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."USERS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."USERS" ADD CONSTRAINT "USERS_CHK1" CHECK (ROLE IN ('normal', 'admin')) ENABLE;
 
  ALTER TABLE "EMI"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EMI"."USERS" ADD CONSTRAINT "USERS_UK1" UNIQUE ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_TASK
--------------------------------------------------------

  ALTER TABLE "EMI"."USER_TASK" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."USER_TASK" MODIFY ("TASK_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMI"."USER_TASK" ADD CONSTRAINT "USER_TASK_UK1" UNIQUE ("USER_ID", "TASK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ANALYSIS
--------------------------------------------------------

  ALTER TABLE "EMI"."ANALYSIS" ADD CONSTRAINT "ANALYSIS_ANALYSISSETTING_FK1" FOREIGN KEY ("SETTING")
	  REFERENCES "EMI"."ANALYSISSETTING" ("ID") ENABLE;
 
  ALTER TABLE "EMI"."ANALYSIS" ADD CONSTRAINT "ANALYSIS_ANALYSISTYPE_FK1" FOREIGN KEY ("TYPE")
	  REFERENCES "EMI"."ANALYSISTYPE" ("ID") ENABLE;
 
  ALTER TABLE "EMI"."ANALYSIS" ADD CONSTRAINT "ANALYSIS_USERS_FK1" FOREIGN KEY ("ANALYZER")
	  REFERENCES "EMI"."USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ANALYSISSETTING
--------------------------------------------------------

  ALTER TABLE "EMI"."ANALYSISSETTING" ADD CONSTRAINT "ANALYSISSETTING_CHANNELSE_FK1" FOREIGN KEY ("CHANNELSETTINGFILE")
	  REFERENCES "EMI"."CHANNELSETTINGFILE" ("ID") ENABLE;
 
  ALTER TABLE "EMI"."ANALYSISSETTING" ADD CONSTRAINT "ANALYSISSETTING_EMIFILE_FK1" FOREIGN KEY ("PRIMARYEMIFILE")
	  REFERENCES "EMI"."EMIFILE" ("ID") ENABLE;
 
  ALTER TABLE "EMI"."ANALYSISSETTING" ADD CONSTRAINT "ANALYSISSETTING_EMIFILE_FK2" FOREIGN KEY ("SECONDARYEMIFILE")
	  REFERENCES "EMI"."EMIFILE" ("ID") ENABLE;
 
  ALTER TABLE "EMI"."ANALYSISSETTING" ADD CONSTRAINT "ANALYSISSETTING_EQUIPMENT_FK1" FOREIGN KEY ("EQUIPMENTPARAMETERFILE")
	  REFERENCES "EMI"."EQUIPMENTPARAMETERFILE" ("ID") ENABLE;
 
  ALTER TABLE "EMI"."ANALYSISSETTING" ADD CONSTRAINT "ANALYSISSETTING_LINKCONFI_FK1" FOREIGN KEY ("LINKCONFIGURATIONFILE")
	  REFERENCES "EMI"."LINKCONFIGURATIONFILE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGION
--------------------------------------------------------

  ALTER TABLE "EMI"."REGION" ADD CONSTRAINT "REGION_CREATOR_FK" FOREIGN KEY ("CREATOR")
	  REFERENCES "EMI"."USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGION_CHANNELSETTINGFILE
--------------------------------------------------------

  ALTER TABLE "EMI"."REGION_CHANNELSETTINGFILE" ADD CONSTRAINT "REGION_CHANNELSETTINGFILE_FK1" FOREIGN KEY ("REGION_ID")
	  REFERENCES "EMI"."REGION" ("ID") ENABLE;
 
  ALTER TABLE "EMI"."REGION_CHANNELSETTINGFILE" ADD CONSTRAINT "REGION_CHANNELSETTINGFILE_FK2" FOREIGN KEY ("CHANNELSETTINGFILE_ID")
	  REFERENCES "EMI"."CHANNELSETTINGFILE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGION_EQUIPMENTPARAMETERFILE
--------------------------------------------------------

  ALTER TABLE "EMI"."REGION_EQUIPMENTPARAMETERFILE" ADD CONSTRAINT "REGION_EQUIPMENTPARAMETER_FK1" FOREIGN KEY ("REGION_ID")
	  REFERENCES "EMI"."REGION" ("ID") ENABLE;
 
  ALTER TABLE "EMI"."REGION_EQUIPMENTPARAMETERFILE" ADD CONSTRAINT "REGION_EQUIPMENTPARAMETER_FK2" FOREIGN KEY ("EQUIPMENTPARAMETERFILE_ID")
	  REFERENCES "EMI"."EQUIPMENTPARAMETERFILE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGION_LINKCONFIGURATIONFILE
--------------------------------------------------------

  ALTER TABLE "EMI"."REGION_LINKCONFIGURATIONFILE" ADD CONSTRAINT "REGION_LINKCONFIGURATIONF_FK1" FOREIGN KEY ("REION_ID")
	  REFERENCES "EMI"."REGION" ("ID") ENABLE;
 
  ALTER TABLE "EMI"."REGION_LINKCONFIGURATIONFILE" ADD CONSTRAINT "REGION_LINKCONFIGURATIONF_FK2" FOREIGN KEY ("LINKCONFIGURATIONFILE_ID")
	  REFERENCES "EMI"."LINKCONFIGURATIONFILE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGION_MANAGER
--------------------------------------------------------

  ALTER TABLE "EMI"."REGION_MANAGER" ADD CONSTRAINT "REGION_MANAGER_REGION_FK1" FOREIGN KEY ("REGION_ID")
	  REFERENCES "EMI"."REGION" ("ID") ENABLE;
 
  ALTER TABLE "EMI"."REGION_MANAGER" ADD CONSTRAINT "REGION_MANAGER_USERS_FK1" FOREIGN KEY ("MANAGER_ID")
	  REFERENCES "EMI"."USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGION_SITE
--------------------------------------------------------

  ALTER TABLE "EMI"."REGION_SITE" ADD CONSTRAINT "REGION_SITE_REGION_FK1" FOREIGN KEY ("REGION_ID")
	  REFERENCES "EMI"."REGION" ("ID") ENABLE;
 
  ALTER TABLE "EMI"."REGION_SITE" ADD CONSTRAINT "REGION_SITE_SITE_FK1" FOREIGN KEY ("SITE_ID")
	  REFERENCES "EMI"."SITE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGION_STRUCTURE
--------------------------------------------------------

  ALTER TABLE "EMI"."REGION_STRUCTURE" ADD CONSTRAINT "REGION_STRUCTURE_REGION_FK1" FOREIGN KEY ("REGION_ID")
	  REFERENCES "EMI"."REGION" ("ID") ENABLE;
 
  ALTER TABLE "EMI"."REGION_STRUCTURE" ADD CONSTRAINT "REGION_STRUCTURE_REGION_FK2" FOREIGN KEY ("SUB_REGION_ID")
	  REFERENCES "EMI"."REGION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TASK
--------------------------------------------------------

  ALTER TABLE "EMI"."TASK" ADD CONSTRAINT "TASK_REGION_FK1" FOREIGN KEY ("REGIONID")
	  REFERENCES "EMI"."REGION" ("ID") ENABLE;
 
  ALTER TABLE "EMI"."TASK" ADD CONSTRAINT "TASK_USERS_FK1" FOREIGN KEY ("CREATOR")
	  REFERENCES "EMI"."USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TASK_ANALYSIS
--------------------------------------------------------

  ALTER TABLE "EMI"."TASK_ANALYSIS" ADD CONSTRAINT "TASK_ANALYSIS_ANALYSIS_FK1" FOREIGN KEY ("ANALYSIS_ID")
	  REFERENCES "EMI"."ANALYSIS" ("ID") ENABLE;
 
  ALTER TABLE "EMI"."TASK_ANALYSIS" ADD CONSTRAINT "TASK_ANALYSIS_TASK_FK1" FOREIGN KEY ("TASK_ID")
	  REFERENCES "EMI"."TASK" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_TASK
--------------------------------------------------------

  ALTER TABLE "EMI"."USER_TASK" ADD CONSTRAINT "USER_TASK_TASK_FK1" FOREIGN KEY ("TASK_ID")
	  REFERENCES "EMI"."TASK" ("ID") ENABLE;
 
  ALTER TABLE "EMI"."USER_TASK" ADD CONSTRAINT "USER_TASK_USERS_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "EMI"."USERS" ("ID") ENABLE;
