/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Dongle */

#ifndef _Included_Dongle
#define _Included_Dongle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Dongle
 * Method:    getAvailableUserCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Dongle_getAvailableUserCount
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
